### ISSUE TITLE
property hide undefined

### ISSUE THREAD

**Issue by wangdongsong** [GoshPosh/grafana-meta-queries#23]
TypeError: Cannot set property 'hide' of undefined
    at eval (http://host.121:3000/public/app/plugins/datasource/goshposh-metaqueries-datasource/datasource.js?bust=1523514908107:113:25)
    at f (http://host.121:3000/public/app/boot.85c49108.js:48:28473)
    at Function.Pg (http://host.121:3000/public/app/boot.85c49108.js:49:29427)
    at MetaQueriesDatasource._doQuery (http://host.121:3000/public/app/plugins/datasource/goshposh-metaqueries-datasource/datasource.js?bust=1523514908107:96:9)
    at eval (http://host.121:3000/public/app/plugins/datasource/goshposh-metaqueries-datasource/datasource.js?bust=1523514908107:52:27)
    at http://host.121:3000/public/app/boot.85c49108.js:49:14624
    at Vc (http://host.121:3000/public/app/boot.85c49108.js:49:5088)
    at http://host.121:3000/public/app/boot.85c49108.js:49:14434
    at Function.Pg (http://host.121:3000/public/app/boot.85c49108.js:49:29427)
    at MetaQueriesDatasource.query (http://host.121:3000/public/app/plugins/datasource/goshposh-metaqueries-datasource/datasource.js?bust=1523514908107:47:9)

**Comment by Gauravshah** [comment]
can you send screenshot of dashboard  config ?
I think you have not set panel source to "meta queries"

**Comment by wangdongsong** [comment]
![grafana-meta-query](https://user-images.githubusercontent.com/3016317/38713767-6daa9c2c-3f05-11e8-816f-ab987a115896.JPG)

**Comment by Gauravshah** [comment]
1st query needs to be influx, second query can reference the first one over PM
