### ISSUE TITLE
where is "grafana mixed panal plugin"

### ISSUE THREAD

**Issue by lastboy1228** [GoshPosh/grafana-meta-queries#3]
Grafana 4.6.1
`TypeError: Cannot set property 'hide' of undefined
    at eval (http://10.24.64.233:3000/public/plugins/grafana-meta-queries-datasource/datasource.js?bust=1510059477301:113:25)
    at f (http://10.24.64.233:3000/public/app/boot.d709d8d5.js:61:30416)
    at Function.Pg (http://10.24.64.233:3000/public/app/boot.d709d8d5.js:62:31351)
    at MetaQueriesDatasource._doQuery (http://10.24.64.233:3000/public/plugins/grafana-meta-queries-datasource/datasource.js?bust=1510059477301:96:9)`

And I really don't understand what "Need to change grafana mixed panal plugin for the plugin to work" means. In the graph panel, there is already --Mixed-- datasource.

**Comment by Gauravshah** [comment]
will update readme for instructions for installation. Regular plugin install should do.
Looks like the "Query" & "Metric" value is incorrect. If you can send screenshot of your configuration we can debug

**Comment by lastboy1228** [comment]
I add two metrics using MetaQueries as datasource, then delete one of them, and the error gone.

**Comment by Gauravshah** [comment]
added more details to readme
