### ISSUE TITLE
Fail to display expression result in table

### ISSUE THREAD

**Issue by lilachmaliniak** [GoshPosh/grafana-meta-queries#9]
Purpose: create table containing columns for hostname, and node status up/down 
The table datasource set to "MetaQuery Datasource"
**added 2 queries:**
 * $datasource is a template parameter containing Elasticsearch (ES) datasource value
A ($datasource) Metrics: Max(private_data.timestamp), Group by:Term(private_data.kes_hostname.keyword)
B (MetaQuery Datasource) Type Arithmetic Expression ((new Date()).getTime() - A['_value']) < 300000 ? 'up' : 'down'
Query A returns expected value and it is successfully displayed in the table.
but, I fail to display a column with the expression value from query B, get error "cannot read property 'length' of undefined". Table cannot be displayed
**stack trace (replacing the ip by A.B.C.D):**
TypeError: Cannot read property 'length' of undefined
    at eval (http:///A.B.C.D:3000/public/plugins/goshposh-metaqueries-datasource/datasource.js?bust=1513782283785:215:68)
    at i (http:///A.B.C.D:3000/public/app/boot.e4836696.js:61:3972)
    at http://A.B.C.D:3000/public/app/boot.e4836696.js:61:4394
    at o.$eval (http:///A.B.C.D:3000/public/app/boot.e4836696.js:61:11549)
    at o.$digest (http:///A.B.C.D:3000/public/app/boot.e4836696.js:61:10022)
    at o.$apply (http:///A.B.C.D:3000/public/app/boot.e4836696.js:61:11832)
    at http:///A.B.C.D:3000/public/app/boot.e4836696.js:61:7882
    at f (http:///A.B.C.D:3000/public/app/boot.e4836696.js:59:22132)
    at http:///A.B.C.D:3000/public/app/boot.e4836696.js:59:23593

**Comment by Gauravshah** [comment]
@lilachmaliniak can you try pulling latest master ? added some defensive code, unsure of underlying issue.

**Comment by lilachmaliniak** [comment]
Hey @Gauravshah,
pulled latest master updates and restarted grafana-server.
get same error:
TypeError: Cannot read property 'length' of undefined
   stack looks the same.
Do you want me to send additional info?

**Comment by Gauravshah** [comment]
the stack trace should have been different. can you clear browser cache & try to load ? I am unable to reproduce the scenario on my end.

**Comment by lilachmaliniak** [comment]
Hey @Gauravshah,
Main datasource in Metrics tab: MetaQuery datasource
A: source: MetaQuery datasource, query: ((new Date()).getTime() - B['_value']) < 300000 ? 'up' : 'down'
B: source: $datasource, query: Max private_data.timestamp, Group by: private_data.kes_hostname.keyword

Important: when the query from ES is the topmost in the Metrics, the MetaQuery query is not processed and that Table can contain the Term and value form the ES query.
When I switch the order of the queries so the MetaQuery query is the topmost, then I get the exception.
I support correct order is that the ES query will be the first, but it seems that using that order the 2nd query is not processed and I fail to define column based on value. 
I prepared a new stack from chrome:
{panelId: 1, range: {…}, rangeRaw: {…}, interval: "2s", intervalMs: 2000, …}
boot.e4836696.js:73 Panel data error: TypeError: Cannot read property 'length' of undefined
    at Object.transform (boot.e4836696.js:30)
    at f.c [as transformDataToTable] (boot.e4836696.js:30)
    at b.render (boot.e4836696.js:30)
    at b.onDataReceived (boot.e4836696.js:30)
    at f.emit (boot.e4836696.js:74)
    at a.emit (boot.e4836696.js:74)
    at b.handleQueryResult (boot.e4836696.js:73)
    at i (boot.e4836696.js:61)
    at boot.e4836696.js:61
    at o.$eval (boot.e4836696.js:61)
datasource.js?bust=1514979272875:39 Do query
datasource.js?bust=1514979272875:40 {panelId: 1, range: {…}, rangeRaw: {…}, interval: "5s", intervalMs: 5000, …}
boot.e4836696.js:73 Panel data error: TypeError: Cannot read property 'length' of undefined
    at Object.transform (boot.e4836696.js:30)
    at f.c [as transformDataToTable] (boot.e4836696.js:30)
    at b.render (boot.e4836696.js:30)
    at b.onDataReceived (boot.e4836696.js:30)
    at f.emit (boot.e4836696.js:74)
    at a.emit (boot.e4836696.js:74)
    at b.handleQueryResult (boot.e4836696.js:73)
    at i (boot.e4836696.js:61)
    at boot.e4836696.js:61
    at o.$eval (boot.e4836696.js:61)

The js stack from grafana:
Cannot read property 'length' of undefined
Stack trace:
TypeError: Cannot read property 'length' of undefined
    at Object.transform (http://x.x.x.x:3000/public/app/boot.e4836696.js:30:11582)
    at f.c [as transformDataToTable] (http://x.x.x.x:3000/public/app/boot.e4836696.js:30:11140)
    at b.render (http://x.x.x.x:3000/public/app/boot.e4836696.js:30:25639)
    at b.onDataReceived (http://x.x.x.x:3000/public/app/boot.e4836696.js:30:25579)
    at f.emit (http:/x.x.x.x:3000/public/app/boot.e4836696.js:74:1714)
    at a.emit (http:/x.x.x.x:3000/public/app/boot.e4836696.js:74:4032)
    at b.handleQueryResult (http://192.168.193.27:3000/public/app/boot.e4836696.js:73:25565)
    at i (http://x.x.x.x:3000/public/app/boot.e4836696.js:61:3972)
    at http://x.x.x.x:3000/public/app/boot.e4836696.js:61:4394
    at o.$eval (http://x.x.x.x:3000/public/app/boot.e4836696.js:61:11549)

**Comment by Gauravshah** [comment]
@lilachmaliniak  can you try swapping the order.
Make `A` from ES and `B` from meta queries ?

**Comment by lilachmaliniak** [comment]
@Gauravshah,
Hey,
Sorry, tried above but it didn't do any change.
